import { AlertCircle } from 'lucide-react';
import StatusBadge from '../components/StatusBadge';
import { mockExplanations } from '../data/mockData';

export default function AiExplanation() {
  return (
    <div className="page">
      <div className="page-header">
        <h1>AI Explanation</h1>
        <p>Easy explanations of your test results</p>
      </div>

      <div className="explanations-grid">
        {mockExplanations.map((item) => (
          <article key={item.title} className="explanation-card">
            <div className="explanation-card__header">
              <h3 className="explanation-card__title">{item.title}</h3>
              <StatusBadge label={item.status} variant={item.variant} />
            </div>
            <p className="explanation-card__body">{item.description}</p>
          </article>
        ))}
      </div>

      <div className="disclaimer">
        <AlertCircle size={18} style={{ verticalAlign: 'middle', marginRight: '0.55rem' }} />
        Note: This explanation is generated by AI and is not a substitute for professional medical advice.
      </div>
    </div>
  );
}